spring:
  application:
    name: common-redis
  redis:
    database: 1 #使用哪个数据库
    host: 192.168.233.128
    port: 6379
    password: aspirine
    timeout: 2000 #链接超时时间
    jedis:
      pool:
        max-active: 200 #最大连接数
        max-wait: -1 #连接池最大等待时间(-1表示无限制)
        max-idle: 10 #连接池最大空闲数
        min-idle: 0 #连接池最小空闲数
  rabbitmq:
    addresses: 192.168.233.128
    username: root
    password: root
    port: 5672
    virtual-host: /

server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

#配置缓存首页商品分类的Key
frontend_catResult_redis_key: frontend:catResult:redis:key

#配置缓存首页大广告位的Key(89表示大广告）
frontend_ad_redis_key: frontend:ad:redis:key:89

#缓存商品基本信息的Key
frontend_item_basic_info_key: frontend:item:basic:info:key

#缓存商品介绍的key
frontend_item_desc_key: frontend:item:desc:key

#缓存商品规格参数的Key
frontend_item_param_key: frontend:item:param:key

#缓存用户的Key
user_session_redis_key: user:session:redis:key

#缓存购物车的Key
frontend_cart_redis_key: frontend:cart:redis:key

#缓存订单ID的Key
order_item_id_key: order:item:id:key

#订单ID初始值的Key
init_item_id: 2000