spring:
  application:
    name: frontend-sso
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: aspirine
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    addresses: 192.168.233.128
    username: root
    password: root
    port: 5672
    virtual-host: /

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

tx-lcn:
  client:
    manager-address: 192.168.233.128:8070


#临时购物车的Key
cart_cookie_name: CART_COOKIE_NAME
