spring:
  application:
    name: frontend-cart
  rabbitmq:
    addresses: 192.168.233.128
    username: root
    password: root
    port: 5672
    virtual-host: /

server:
  port: 9040

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

#临时购物车的Key
cart_cookie_name: CART_COOKIE_NAME