spring:
  application:
    name: frontend-portal
  rabbitmq:
    addresses: 192.168.233.128
    username: root
    password: root
    port: 5672
    virtual-host: /

server:
  port: 9030

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

#feign开启hystrix的熔断机制，默认不开启
feign:
  hystrix:
    enabled: true


